<?php

/**
 * @file
 * Module billing_invoice.module.
 */

/**
 * Implements hook_theme().
 */
function billing_invoice_theme() {
  $theme = [];
  $theme['billing_invoice'] = [
    'render element' => 'elements',
    'file' => 'billing_invoice.page.inc',
    'template' => 'billing_invoice',
  ];
  $theme['billing_invoice_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'billing_invoice.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function billing_invoice_theme_suggestions_billing_invoice(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#billing_invoice'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'billing_invoice__' . $sanitized_view_mode;
  $suggestions[] = 'billing_invoice__' . $entity->bundle();
  $suggestions[] = 'billing_invoice__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'billing_invoice__' . $entity->id();
  $suggestions[] = 'billing_invoice__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
