<?php

/**
 * @file
 * Module billing.module.
 */

/**
 * Implements hook_theme().
 */
function billing_theme() {
  $theme = [];
  $theme['billing_purchase'] = [
    'render element' => 'elements',
    'file' => 'billing_purchase.page.inc',
    'template' => 'billing_purchase',
  ];
  $theme['billing_purchase_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'billing_purchase.page.inc',
  ];
  $theme['billing_invoice'] = [
    'render element' => 'elements',
    'file' => 'billing_invoice.page.inc',
    'template' => 'billing_invoice',
  ];
  $theme['billing_invoice_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'billing_invoice.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function billing_theme_suggestions_billing_purchase(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#billing_purchase'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'billing_purchase__' . $sanitized_view_mode;
  $suggestions[] = 'billing_purchase__' . $entity->bundle();
  $suggestions[] = 'billing_purchase__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'billing_purchase__' . $entity->id();
  $suggestions[] = 'billing_purchase__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function billing_theme_suggestions_billing_invoice(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#billing_invoice'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'billing_invoice__' . $sanitized_view_mode;
  $suggestions[] = 'billing_invoice__' . $entity->bundle();
  $suggestions[] = 'billing_invoice__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'billing_invoice__' . $entity->id();
  $suggestions[] = 'billing_invoice__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
